# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_acl', '0003_default_roles'),
        ('misago_acl', '0006_status_roles'),
    ]

    operations = [
    ]
