# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_categories', '0006_moderation_queue_roles'),
        ('misago_categories', '0007_privatethread_category'),
    ]

    operations = [
    ]
