# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0010_user_profile_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'get_latest_by': 'order'},
        ),
        migrations.AlterModelOptions(
            name='usernamechange',
            options={'get_latest_by': 'changed_on'},
        ),
    ]
